/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GiaoDien;

import GiaodienIn.Bosung;
import IOfile.IO;
import InforSQL.DoiGV;
import InforSQL.GiangVien;
import InforSQL.PheDuyet;
import InforSQL.SinhVien;
import InforSQL.ThongTinLop;
import LopInf.LopInf;
import PheDuyet.SqlDuyet;
import User.User;
import java.awt.Color;
import java.awt.Component;
import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.List;
import java.util.Random;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTabbedPane;
import javax.swing.JTable;
import javax.swing.SwingConstants;
import javax.swing.Timer;
import javax.swing.UIManager;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;
import javax.swing.table.TableModel;
import java.time.LocalDateTime;
import java.sql.Timestamp;

/**
 *
 * @author ADMIN
 */
public class Admin extends javax.swing.JFrame {

    /**
     * Creates new form Admin
     */
  
     DefaultTableModel defaultb = new DefaultTableModel() ;
      DefaultTableModel defaultb2 = new DefaultTableModel() ;
       DefaultTableModel defaultb3 = new DefaultTableModel();
       DefaultTableModel defaultb4 = new DefaultTableModel();
     IO w = new IO();
     int ChonKN =0;
     int LuaChon=0;
      LopInf lopInf;
    public Admin() {
        initComponents();
        this.setLocationRelativeTo(null);
        ImageIcon icon = new ImageIcon("src/Anhdd/logo.png");
        Image img = icon.getImage();
        Image imgScale = img.getScaledInstance(jLabel1.getWidth(), jLabel1.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon scaleIcon = new ImageIcon(imgScale);
        jLabel1.setIcon(scaleIcon);
        table tb = new table();
        table1 tb1 = new table1();
        table2 tb2 = new table2();
        table3 tb3 = new table3();
        table4 tb4 = new table4();
        jButton11.setVisible(false);
        jButton12.setVisible(false);
        jButton14.setVisible(false);
        jButton15.setVisible(false);
        

       

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jButton6 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTable4 = new javax.swing.JTable();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jTextField3 = new javax.swing.JTextField();
        jButton13 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 127, Short.MAX_VALUE)
        );

        jTabbedPane1.setBackground(new java.awt.Color(204, 204, 255));
        jTabbedPane1.setForeground(new java.awt.Color(255, 102, 102));
        jTabbedPane1.setTabLayoutPolicy(javax.swing.JTabbedPane.SCROLL_TAB_LAYOUT);
        jTabbedPane1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jTabbedPane1.setOpaque(true);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setForeground(new java.awt.Color(204, 255, 255));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.setRowHeight(25);
        jTable1.setSelectionBackground(new java.awt.Color(204, 204, 255));
        jTable1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jTable1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane2.setViewportView(jTable1);

        jLabel2.setText("Nhập MSSV (hoặc tên)");

        jButton1.setBackground(new java.awt.Color(204, 204, 255));
        jButton1.setForeground(new java.awt.Color(255, 0, 0));
        jButton1.setText("Tìm kiếm");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Chỉnh sửa");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Cập nhật");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Xóa");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("Thêm sinh viên");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jScrollPane2)
                .addContainerGap())
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(355, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton5)
                .addGap(56, 56, 56)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(61, 61, 61)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(78, 78, 78)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(111, 111, 111))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jButton1))
                .addGap(28, 28, 28)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addComponent(jButton2)
                    .addComponent(jButton4)
                    .addComponent(jButton5))
                .addContainerGap(270, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("QUẢN LÝ SINH VIÊN", jPanel3);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable2.setRowHeight(25);
        jTable2.setSelectionBackground(new java.awt.Color(204, 204, 255));
        jTable2.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jTable2.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane3.setViewportView(jTable2);

        jButton6.setText("Tìm kiếm");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jLabel3.setText("Nhập MSGV (Hoặc Tên)");

        jButton7.setText("Thêm");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton8.setText("Xóa");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jButton9.setText("Chỉnh sửa");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jButton10.setText("Cập nhật");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(124, 124, 124)
                .addComponent(jLabel3)
                .addGap(41, 41, 41)
                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(61, 61, 61)
                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(319, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(61, 61, 61)
                .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52)
                .addComponent(jButton9)
                .addGap(50, 50, 50)
                .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(83, 83, 83))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton6)
                    .addComponent(jLabel3)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton10)
                    .addComponent(jButton9)
                    .addComponent(jButton8)
                    .addComponent(jButton7))
                .addContainerGap(309, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("QUẢN LÝ GIẢNG VIÊN", jPanel4);

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        jTable4.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable4.setRowHeight(25);
        jTable4.setSelectionBackground(new java.awt.Color(204, 204, 255));
        jTable4.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jTable4.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane5.setViewportView(jTable4);

        buttonGroup2.add(jRadioButton3);
        jRadioButton3.setSelected(true);
        jRadioButton3.setText("Tất cả các lớp");
        jRadioButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton3ActionPerformed(evt);
            }
        });

        buttonGroup2.add(jRadioButton4);
        jRadioButton4.setText("Lớp không đạt");
        jRadioButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton4ActionPerformed(evt);
            }
        });

        jButton13.setText("Tìm Kiếm");
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });

        jButton14.setText("Xóa");
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });

        jButton15.setText("Xóa tất");
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jRadioButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43)
                        .addComponent(jRadioButton4)
                        .addGap(142, 142, 142)
                        .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)
                        .addComponent(jButton13, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 695, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(97, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton15, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(jButton14, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(231, 231, 231))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jRadioButton3)
                            .addComponent(jRadioButton4)))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton13))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton14)
                    .addComponent(jButton15))
                .addContainerGap(223, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("QUẢN LÝ LỚP", jPanel5);

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setSelected(true);
        jRadioButton1.setText("Chờ phê duyệt");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setText("Đã phê duyệt");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jTable3.setRowHeight(25);
        jTable3.setSelectionBackground(new java.awt.Color(204, 204, 255));
        jTable3.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jTable3.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jTable3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable3MouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(jTable3);

        jButton11.setText("Không đồng ý");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });

        jButton12.setText("Đồng Ý");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(137, 137, 137)
                        .addComponent(jRadioButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(70, 70, 70)
                        .addComponent(jRadioButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(94, 94, 94)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 610, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(171, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton11)
                .addGap(18, 18, 18)
                .addComponent(jButton12, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(223, 223, 223))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton1)
                    .addComponent(jRadioButton2))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton12)
                    .addComponent(jButton11))
                .addContainerGap(300, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("ĐƠN TỪ", jPanel6);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jSeparator1)
            .addComponent(jTabbedPane1)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1))
        );

        jScrollPane1.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 717, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
          if(jTable1.getSelectedRowCount()>0)
        {
        
             int x = jTable1.getSelectedRow();
             String code = String.valueOf(jTable1.getValueAt(x, 1));
             w.writeFileTtSv(code);
             new ChangeInf().setVisible(true);
           
        }
        else
        {
            JFrame frame = new JFrame("JOptionPane showMessageDialog example");
                 JOptionPane.showMessageDialog(frame, "Chưa chọn sinh viên", "Báo lỗi", JOptionPane.INFORMATION_MESSAGE);
        }
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String str = jTextField1.getText();
        User user = new User();
       
        defaultb.setRowCount(0);
       
        List<SinhVien> sv = user.getInf(str);
        int m=1;
        for(SinhVien tt : sv)
        {
            String gt = new String();
            if(tt.getGioiTinh()) gt = "Nam";
            else gt = "Nữ";
            defaultb.addRow(new Object[] {m,tt.getIDSV(),tt.getName(),tt.getNgaysinh(),gt,tt.getMaKhoa(),tt.getDiaChi()});
            m++;
        }
        DefaultTableCellRenderer rightRenderer = new DefaultTableCellRenderer();
        rightRenderer.setHorizontalAlignment(SwingConstants.CENTER);
 
        TableModel tableModel = jTable1.getModel();
 
        for (int columnIndex = 0; columnIndex < tableModel.getColumnCount(); columnIndex++)
        {
            jTable1.getColumnModel().getColumn(columnIndex).setCellRenderer(rightRenderer);
        }
    
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
         User user = new User();
       
        defaultb.setRowCount(0);
       
        List<SinhVien> sv = user.getInf("");
        int m=1;
        for(SinhVien tt : sv)
        {
            String gt = new String();
            if(tt.getGioiTinh()) gt = "Nam";
            else gt = "Nữ";
            defaultb.addRow(new Object[] {m,tt.getIDSV(),tt.getName(),tt.getNgaysinh(),gt,tt.getMaKhoa(),tt.getDiaChi()});
            m++;
        }
        DefaultTableCellRenderer rightRenderer = new DefaultTableCellRenderer();
        rightRenderer.setHorizontalAlignment(SwingConstants.CENTER);
 
        TableModel tableModel = jTable1.getModel();
 
        for (int columnIndex = 0; columnIndex < tableModel.getColumnCount(); columnIndex++)
        {
            jTable1.getColumnModel().getColumn(columnIndex).setCellRenderer(rightRenderer);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
          if(jTable1.getSelectedRowCount()>0)
        {
        
             JFrame frame = new JFrame("JOptionPane showMessageDialog example");
               int x=  JOptionPane.showConfirmDialog(frame, "Bạn có chắc là muốn xóa", "Cảnh báo", JOptionPane.YES_NO_OPTION);
               if(x ==JOptionPane.YES_OPTION) 
               {
               int y = jTable1.getSelectedRow();
               String code = String.valueOf(jTable1.getValueAt(y, 1));
               User user = new User();
               user.deleteTT(code);
               
             
               }
           
        }
        else
        {
            JFrame frame = new JFrame("JOptionPane showMessageDialog example");
                 JOptionPane.showMessageDialog(frame, "Chưa chọn sinh viên", "Báo lỗi", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        new InsertGV().setVisible(true);
        
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        new InsertSV().setVisible(true);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
         String str = jTextField2.getText();
        User user = new User();
       
        defaultb2.setRowCount(0);
       
        List<GiangVien> sv = user.getInfGV(str);
        int m=1;
        for(GiangVien tt : sv)
        {
            String gt = new String();
            if(tt.getGioiTinh()) gt = "Nam";
            else gt = "Nữ";
            defaultb2.addRow(new Object[] {m,tt.getIDGV(),tt.getNameGV(),tt.getNgaysinh(),gt,tt.getMaKhoa(),tt.getDiaChi()});
            m++;
        }
        DefaultTableCellRenderer rightRenderer = new DefaultTableCellRenderer();
        rightRenderer.setHorizontalAlignment(SwingConstants.CENTER);
 
        TableModel tableModel = jTable1.getModel();
 
        for (int columnIndex = 0; columnIndex < tableModel.getColumnCount(); columnIndex++)
        {
            jTable1.getColumnModel().getColumn(columnIndex).setCellRenderer(rightRenderer);
        }
        
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        if(jTable2.getSelectedRowCount()>0)
        {
        
             JFrame frame = new JFrame("JOptionPane showMessageDialog example");
               int x=  JOptionPane.showConfirmDialog(frame, "Bạn có chắc là muốn xóa", "Cảnh báo", JOptionPane.YES_NO_OPTION);
               if(x ==JOptionPane.YES_OPTION) 
               {
               int y = jTable2.getSelectedRow();
               String code = String.valueOf(jTable2.getValueAt(y, 1));
               User user = new User();
               user.deleteTTGv(code);
               
             
               }
           
        }
        else
        {
            JFrame frame = new JFrame("JOptionPane showMessageDialog example");
                 JOptionPane.showMessageDialog(frame, "Chưa chọn Giảng Viên", "Báo lỗi", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
        
        User user = new User();
       
        defaultb2.setRowCount(0);
       
        List<GiangVien> sv = user.getInfGV("");
        int m=1;
        for(GiangVien tt : sv)
        {
            String gt = new String();
            if(tt.getGioiTinh()) gt = "Nam";
            else gt = "Nữ";
            defaultb2.addRow(new Object[] {m,tt.getIDGV(),tt.getNameGV(),tt.getNgaysinh(),gt,tt.getMaKhoa(),tt.getDiaChi()});
            m++;
        }
        DefaultTableCellRenderer rightRenderer = new DefaultTableCellRenderer();
        rightRenderer.setHorizontalAlignment(SwingConstants.CENTER);
 
        TableModel tableModel = jTable1.getModel();
 
        for (int columnIndex = 0; columnIndex < tableModel.getColumnCount(); columnIndex++)
        {
            jTable1.getColumnModel().getColumn(columnIndex).setCellRenderer(rightRenderer);
        }
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
          if(jTable2.getSelectedRowCount()>0)
        {
        
             int x = jTable2.getSelectedRow();
             String code = String.valueOf(jTable2.getValueAt(x, 1));
             w.writeFileTtGv(code);
             new ChangeInfGV().setVisible(true);
           
        }
        else
        {
            JFrame frame = new JFrame("JOptionPane showMessageDialog example");
                 JOptionPane.showMessageDialog(frame, "Chưa chọn Giảng Viên", "Báo lỗi", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
        ChonKN =0;
        table3 tb3 = new table3();
        jButton11.setVisible(true);
        jButton12.setVisible(true);
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jTable3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable3MouseClicked
        // TODO add your handling code here:
        
        
        
    }//GEN-LAST:event_jTable3MouseClicked

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        // TODO add your handling code here:
        jButton11.setVisible(false);
        jButton12.setVisible(false);
        ChonKN =1;
        table3 tb3 = new table3();
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        // TODO add your handling code here:
         if(jTable3.getSelectedRowCount()==0)
        {
        
            JFrame frame = new JFrame("JOptionPane showMessageDialog example");
                 JOptionPane.showMessageDialog(frame, "Chưa chọn lớp", "Báo lỗi", JOptionPane.INFORMATION_MESSAGE);
        }
         else
         {
             int x = jTable3.getSelectedRow();
             String code = String.valueOf(jTable3.getValueAt(x, 2));
             String code2 = String.valueOf(jTable3.getValueAt(x, 5));
             Timestamp code4 = Timestamp.valueOf(code);
             DoiGV pd = new DoiGV();
             pd.setThoigiangui(code4);
             pd.setIdlop(code2);
             SqlDuyet sd = new SqlDuyet();
             sd.Tuchoi(pd);
             table3 tb3 = new table3();
             
         
         }
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        // TODO add your handling code here:
        if(jTable3.getSelectedRowCount()==0)
        {
        
            JFrame frame = new JFrame("JOptionPane showMessageDialog example");
                 JOptionPane.showMessageDialog(frame, "Chưa chọn lớp", "Báo lỗi", JOptionPane.INFORMATION_MESSAGE);
        }
         else
         {
            int x = jTable3.getSelectedRow();
             String code = String.valueOf(jTable3.getValueAt(x, 2));
             String code2 = String.valueOf(jTable3.getValueAt(x, 5));
             Timestamp code4 = Timestamp.valueOf(code);
             DoiGV pd = new DoiGV();
             pd.setThoigiangui(code4);
             pd.setIdlop(code2);
             SqlDuyet sd = new SqlDuyet();
             sd.DongY(pd);
             table3 tb3 = new table3();
             
         
         }
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jRadioButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton3ActionPerformed
        // TODO add your handling code here:
        LuaChon=0;
        jButton14.setVisible(false);
        jButton15.setVisible(false);
        table4 tb = new table4();
        
       
        
    }//GEN-LAST:event_jRadioButton3ActionPerformed

    private void jRadioButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton4ActionPerformed
        // TODO add your handling code here:
        LuaChon=1;
         jButton14.setVisible(true);
        jButton15.setVisible(true);
        table4 tb = new table4();
    }//GEN-LAST:event_jRadioButton4ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        // TODO add your handling code here:
        String str = jTextField3.getText();
        if(LuaChon==0)
        {
            lopInf = new LopInf();
            defaultb4.setRowCount(0);
            List<ThongTinLop> Lopkhoa = lopInf.TimLop(str);
        for(ThongTinLop tt : Lopkhoa)
        {
            if(tt.getMaGV().equals("0")) defaultb4.addRow(new Object[]{tt.getMaHP(),tt.getTenHP(),tt.getIDLop(),"NULL",tt.getSiSo()});
            else 
            {
               
                defaultb4.addRow(new Object[]{tt.getMaHP(),tt.getTenHP(),tt.getIDLop(),tt.getMaGV(),tt.getSiSo()});
            }
          
            
        }
        
        jTable4.getColumnModel().getColumn(0).setPreferredWidth(50);
        jTable4.getColumnModel().getColumn(1).setPreferredWidth(170);
        jTable4.getColumnModel().getColumn(2).setPreferredWidth(50);
        jTable4.getColumnModel().getColumn(3).setPreferredWidth(50);
        jTable4.getColumnModel().getColumn(4).setPreferredWidth(70);
        
        jTable4.setAutoResizeMode(JTable.AUTO_RESIZE_LAST_COLUMN);
     
        }
        else
        {
            lopInf = new LopInf();
            defaultb4.setRowCount(0);
            List<ThongTinLop> Lopkhoa = lopInf.TimLopKD(str);
        for(ThongTinLop tt : Lopkhoa)
        {
            if(tt.getMaGV().equals("0")) defaultb4.addRow(new Object[]{tt.getMaHP(),tt.getTenHP(),tt.getIDLop(),"NULL",tt.getSiSo()});
            else 
            {
               
                defaultb4.addRow(new Object[]{tt.getMaHP(),tt.getTenHP(),tt.getIDLop(),tt.getMaGV(),tt.getSiSo()});
            }
          
            
        }
        
        jTable4.getColumnModel().getColumn(0).setPreferredWidth(50);
        jTable4.getColumnModel().getColumn(1).setPreferredWidth(170);
        jTable4.getColumnModel().getColumn(2).setPreferredWidth(50);
        jTable4.getColumnModel().getColumn(3).setPreferredWidth(50);
        jTable4.getColumnModel().getColumn(4).setPreferredWidth(70);
        
        jTable4.setAutoResizeMode(JTable.AUTO_RESIZE_LAST_COLUMN);
        }
    }//GEN-LAST:event_jButton13ActionPerformed

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
        // TODO add your handling code here:
          if(jTable4.getSelectedRowCount()>0)
        {
             JFrame frame = new JFrame("JOptionPane showMessageDialog example");
               int x=  JOptionPane.showConfirmDialog(frame, "Bạn có chắc là muốn xóa", "Cảnh báo", JOptionPane.YES_NO_OPTION);
               if(x ==JOptionPane.YES_OPTION) 
               {
             int y = jTable4.getSelectedRow();
             String code = String.valueOf(jTable4.getValueAt(y, 2));
             lopInf = new LopInf();
             lopInf.XoaLop(code);
               }
               table4 tb = new table4();
           
        }
        else
        {
            JFrame frame = new JFrame("JOptionPane showMessageDialog example");
                 JOptionPane.showMessageDialog(frame, "Chưa chọn lớp", "Báo lỗi", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_jButton14ActionPerformed

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed
        // TODO add your handling code here:
       
             JFrame frame = new JFrame("JOptionPane showMessageDialog example");
               int x=  JOptionPane.showConfirmDialog(frame, "Bạn có chắc là muốn xóa", "Cảnh báo", JOptionPane.YES_NO_OPTION);
               if(x ==JOptionPane.YES_OPTION) 
               {
             
             lopInf = new LopInf();
             lopInf.XoaLopAll();
               }
              table4 tb = new table4();
           
        
    }//GEN-LAST:event_jButton15ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Admin().setVisible(true);
            }
        });
    }
public static class HeaderColor extends DefaultTableCellRenderer
    {
        public HeaderColor()
        {
            setOpaque(true);
        }
        public Component getTableCellRendererComponent(JTable mytable, Object value,boolean selected,boolean focused,int row,int column)
        {
            super.getTableCellRendererComponent(mytable, value, selected, focused, row, column);
            setBackground(new java.awt.Color(255,0,0));
            setForeground(new java.awt.Color(255,255,255));

            return this;
        }
        
    }
public class table
    {
        public table()
        {
        
        jTable1.getTableHeader().setDefaultRenderer(new HeaderColor());
         JTableHeader tb1 = jTable1.getTableHeader();
        ((DefaultTableCellRenderer)tb1.getDefaultRenderer()).setHorizontalAlignment(JLabel.CENTER);
        jTable2.getTableHeader().setDefaultRenderer(new HeaderColor());
         JTableHeader tb2 = jTable2.getTableHeader();
        ((DefaultTableCellRenderer)tb2.getDefaultRenderer()).setHorizontalAlignment(JLabel.CENTER);
        jTable3.getTableHeader().setDefaultRenderer(new HeaderColor());
         JTableHeader tb3 = jTable3.getTableHeader();
        ((DefaultTableCellRenderer)tb3.getDefaultRenderer()).setHorizontalAlignment(JLabel.CENTER);
        jTable3.getTableHeader().setDefaultRenderer(new HeaderColor());
         JTableHeader tb4 = jTable4.getTableHeader();
        ((DefaultTableCellRenderer)tb4.getDefaultRenderer()).setHorizontalAlignment(JLabel.CENTER);
        }
    }
public class table1
{
    public table1()
    {
        User user = new User();
         defaultb = new DefaultTableModel() 
        {
          @Override
    public boolean isCellEditable(int row, int column) {
       //all cells false
       return false;
    }
           };
        jTable1.setModel(defaultb);
        defaultb.addColumn("STT");
        defaultb.addColumn("MSSV");
        defaultb.addColumn("Họ Tên");
        defaultb.addColumn("Ngày sinh");
        defaultb.addColumn("Giới tính");
        defaultb.addColumn("Khoa");
        defaultb.addColumn("Địa chỉ");
        List<SinhVien> sv = user.getALLSV();
        int m=1;
        for(SinhVien tt : sv)
        {
            String gt = new String();
            if(tt.getGioiTinh()) gt = "Nam";
            else gt = "Nữ";
            defaultb.addRow(new Object[] {m,tt.getIDSV(),tt.getName(),tt.getNgaysinh(),gt,tt.getMaKhoa(),tt.getDiaChi()});
            m++;
        }
        DefaultTableCellRenderer rightRenderer = new DefaultTableCellRenderer();
        rightRenderer.setHorizontalAlignment(SwingConstants.CENTER);
 
        TableModel tableModel = jTable1.getModel();
 
        for (int columnIndex = 0; columnIndex < tableModel.getColumnCount(); columnIndex++)
        {
            jTable1.getColumnModel().getColumn(columnIndex).setCellRenderer(rightRenderer);
        }
    }
}
public class table2
{
    public table2()
    {
        User user = new User();
         defaultb2 = new DefaultTableModel() 
        {
          @Override
    public boolean isCellEditable(int row, int column) {
       //all cells false
       return false;
    }
           };
        jTable2.setModel(defaultb2);
        defaultb2.addColumn("STT");
        defaultb2.addColumn("MSGV");
        defaultb2.addColumn("Họ Tên");
        defaultb2.addColumn("Ngày sinh");
        defaultb2.addColumn("Giới tính");
        defaultb2.addColumn("Khoa");
        defaultb2.addColumn("Địa chỉ");
        List<GiangVien> gv = user.getALLGV();
        int m=1;
        for( GiangVien tt : gv)
        {
            String gt = new String();
            if(tt.getGioiTinh()) gt = "Nam";
            else gt = "Nữ";
            defaultb2.addRow(new Object[] {m,tt.getIDGV(),tt.getNameGV(),tt.getNgaysinh(),gt,tt.getMaKhoa(),tt.getDiaChi()});
            m++;
        }
        DefaultTableCellRenderer rightRenderer = new DefaultTableCellRenderer();
        rightRenderer.setHorizontalAlignment(SwingConstants.CENTER);
 
        TableModel tableModel = jTable1.getModel();
 
        for (int columnIndex = 0; columnIndex < tableModel.getColumnCount(); columnIndex++)
        {
            jTable1.getColumnModel().getColumn(columnIndex).setCellRenderer(rightRenderer);
        }
    }
}
public class table3
{
    public table3()
    {
        if(ChonKN==0)
        {
            defaultb3 = new DefaultTableModel()
                {
                    @Override
    public boolean isCellEditable(int row, int column) {
       //all cells false
       return false;
    }
                };
        jTable3.setModel(defaultb3);
        defaultb3.addColumn("STT");
        defaultb3.addColumn("ID");
        defaultb3.addColumn("Thời gian");
        defaultb3.addColumn("Hành động");
         defaultb3.addColumn("GV thay the");
        defaultb3.addColumn("Ma lop");
        defaultb3.addColumn("Lí do");
       
        SqlDuyet duyet = new SqlDuyet();
         List<DoiGV> day= duyet.ThongKeDonCD();
         int stt=1;
        for(DoiGV tt : day)
        {
            String hdong = new String();
            hdong = "Thay đổi giáo viên lớp: ";
            defaultb3.addRow(new Object[]{stt,tt.getNg(),tt.getThoigiangui(),hdong,tt.getIdgv(),tt.getIdlop(),tt.getLido()});
            stt++;
            
        }
        jTable3.getColumnModel().getColumn(0).setPreferredWidth(30);
        jTable3.getColumnModel().getColumn(1).setPreferredWidth(70);
        jTable3.getColumnModel().getColumn(2).setPreferredWidth(50);
        jTable3.getColumnModel().getColumn(3).setPreferredWidth(100);
        jTable3.getColumnModel().getColumn(4).setPreferredWidth(200);
        jTable3.getColumnModel().getColumn(5).setPreferredWidth(200);
        jTable3.setAutoResizeMode(JTable.AUTO_RESIZE_LAST_COLUMN);
        }
        else
        {
            defaultb3 = new DefaultTableModel()
                {
                    @Override
    public boolean isCellEditable(int row, int column) {
       //all cells false
       return false;
    }
                };
        jTable3.setModel(defaultb3);
        defaultb3.addColumn("STT");
        defaultb3.addColumn("ID");
        defaultb3.addColumn("Thời gian");
        defaultb3.addColumn("Hành động");
         defaultb3.addColumn("GV thay the");
        defaultb3.addColumn("Ma lop");
        defaultb3.addColumn("Lí do");
        defaultb3.addColumn("Y/N");
       
        SqlDuyet duyet = new SqlDuyet();
         List<DoiGV> day= duyet.ThongKeDonDD();
         int stt=1;
        for(DoiGV tt : day)
        {
            String hdong = new String();
            hdong = "Thay đổi giáo viên lớp: ";
            defaultb3.addRow(new Object[]{stt,tt.getNg(),tt.getThoigiangui(),hdong,tt.getIdgv(),tt.getIdlop(),tt.getLido(),tt.getDongy()});
            stt++;
            
        }
         jTable3.getColumnModel().getColumn(0).setPreferredWidth(30);
        jTable3.getColumnModel().getColumn(1).setPreferredWidth(70);
        jTable3.getColumnModel().getColumn(2).setPreferredWidth(50);
        jTable3.getColumnModel().getColumn(3).setPreferredWidth(100);
        jTable3.getColumnModel().getColumn(4).setPreferredWidth(200);
        jTable3.getColumnModel().getColumn(5).setPreferredWidth(200);
        jTable3.getColumnModel().getColumn(6).setPreferredWidth(50);
        jTable3.setAutoResizeMode(JTable.AUTO_RESIZE_LAST_COLUMN);
        }
    }
}
  public class table4
    {
        public table4()
        {
            
        if(LuaChon==0)
        {
            
             defaultb4 = new DefaultTableModel()
                {
                    @Override
    public boolean isCellEditable(int row, int column) {
       //all cells false
       return false;
    }
         
             };
             jTable4.setModel(defaultb4);
             defaultb4.addColumn("Mã HP");
             defaultb4.addColumn("Tên học phần");
             defaultb4.addColumn("Mã Lớp");
             defaultb4.addColumn("Mã GV");
           
             defaultb4.addColumn("số sinh viên");
              lopInf = new LopInf();
        List<ThongTinLop> Lopkhoa = lopInf.ALLLopKHoa();
        for(ThongTinLop tt : Lopkhoa)
        {
            if(tt.getMaGV().equals("0")) defaultb4.addRow(new Object[]{tt.getMaHP(),tt.getTenHP(),tt.getIDLop(),"NULL",tt.getSiSo()});
            else 
            {
               
                defaultb4.addRow(new Object[]{tt.getMaHP(),tt.getTenHP(),tt.getIDLop(),tt.getMaGV(),tt.getSiSo()});
            }
          
            
        }
        
        jTable4.getColumnModel().getColumn(0).setPreferredWidth(50);
        jTable4.getColumnModel().getColumn(1).setPreferredWidth(170);
        jTable4.getColumnModel().getColumn(2).setPreferredWidth(50);
        jTable4.getColumnModel().getColumn(3).setPreferredWidth(50);
        jTable4.getColumnModel().getColumn(4).setPreferredWidth(70);
        
        jTable4.setAutoResizeMode(JTable.AUTO_RESIZE_LAST_COLUMN);
     
             
        }
        else
        {
           
          
             defaultb4 = new DefaultTableModel()
                {
                    @Override
    public boolean isCellEditable(int row, int column) {
       //all cells false
       return false;
    }
         
             };
             jTable4.setModel(defaultb4);
             defaultb4.addColumn("Mã HP");
             defaultb4.addColumn("Tên học phần");
             defaultb4.addColumn("Mã Lớp");
             defaultb4.addColumn("Mã GV");
           
             defaultb4.addColumn("số sinh viên");
              lopInf = new LopInf();
        List<ThongTinLop> Lopkhoa = lopInf.ALLLopKD();
        for(ThongTinLop tt : Lopkhoa)
        {
            if(tt.getMaGV().equals("0")) defaultb4.addRow(new Object[]{tt.getMaHP(),tt.getTenHP(),tt.getIDLop(),"NULL",tt.getSiSo()});
            else 
            {
               
                defaultb4.addRow(new Object[]{tt.getMaHP(),tt.getTenHP(),tt.getIDLop(),tt.getMaGV(),tt.getSiSo()});
            }
          
            
        }
        
        jTable4.getColumnModel().getColumn(0).setPreferredWidth(50);
        jTable4.getColumnModel().getColumn(1).setPreferredWidth(170);
        jTable4.getColumnModel().getColumn(2).setPreferredWidth(50);
        jTable4.getColumnModel().getColumn(3).setPreferredWidth(50);
        jTable4.getColumnModel().getColumn(4).setPreferredWidth(70);
        
        jTable4.setAutoResizeMode(JTable.AUTO_RESIZE_LAST_COLUMN);
       
             
        }
            
        }
     
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JTable jTable4;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    // End of variables declaration//GEN-END:variables
}
