/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GiaoDien;

import IOfile.IO;
import InforSQL.DiemSV;
import InforSQL.DonPK;
import InforSQL.LichSuHT;
import InforSQL.PheDuyet;
import InforSQL.SinhVien;
import InforSQL.ThongTinLop;
import LopInf.LopInf;
import PheDuyet.SqlDuyet;
import User.User;
import java.awt.Component;
import java.awt.Image;
import java.io.File;
import java.sql.Timestamp;
import java.time.LocalDateTime;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.SwingConstants;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.JTableHeader;
import javax.swing.table.TableModel;

/**
 *
 * @author ADMIN
 */
public class SVInf extends javax.swing.JFrame {

    /**
     * Creates new form SVInf
     */
    DefaultTableModel defaultb;
    DefaultTableModel defaultb2 ;
    DefaultTableModel defaultb3 ;
    DefaultTableModel defaultb4;
    DefaultTableModel defaultb6;
        LopInf lopInf;
        int b=0;
        User user;
        String sm = new String();
        int ChonHT=1; 
         SinhVien sv1 = new SinhVien();
         PheDuyet PD = new PheDuyet();
         DonPK pd = new DonPK();
         int BIEN = 0;
         int BIEN2=0;
    public SVInf() {
        initComponents();
        this.setLocationRelativeTo(null);
        lopInf = new LopInf();
        IO w = new IO();
        SinhVien sv = new SinhVien();
        sv1=sv;
        w.readFileSV(sv);
        sm=sv.getIDSV();
        tabOne Tab_one = new tabOne(sv);
        TableOne TBOne = new TableOne(sv);
        Table3 TB3 = new Table3(sv);
        Table4 TB4 = new Table4(sv);
        Table5 TB5 = new Table5(sv);
        table tb = new table();
        jButton2.setVisible(false);
        jPanel8.setVisible(false);
         jLabel23.setVisible(false);
        jLabel24.setVisible(false);
         Table_6 tab = new Table_6();
         pd.setIdsv(Integer.parseInt(sv.getIDSV()));
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel6 = new javax.swing.JPanel();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel9 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jSeparator2 = new javax.swing.JSeparator();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable4 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jSeparator6 = new javax.swing.JSeparator();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTable5 = new javax.swing.JTable();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jPanel8 = new javax.swing.JPanel();
        jRadioButton4 = new javax.swing.JRadioButton();
        jRadioButton5 = new javax.swing.JRadioButton();
        jButton3 = new javax.swing.JButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jButton2 = new javax.swing.JButton();
        jRadioButton6 = new javax.swing.JRadioButton();
        jLabel24 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jScrollPane8 = new javax.swing.JScrollPane();
        jTable6 = new javax.swing.JTable();
        jRadioButton7 = new javax.swing.JRadioButton();
        jRadioButton8 = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setPreferredSize(new java.awt.Dimension(930, 750));
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jSeparator1);

        jPanel5.setLayout(null);
        getContentPane().add(jPanel5);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jTabbedPane1.setBackground(new java.awt.Color(255, 255, 255));
        jTabbedPane1.setBorder(new javax.swing.border.MatteBorder(null));
        jTabbedPane1.setForeground(new java.awt.Color(255, 0, 0));
        jTabbedPane1.setTabLayoutPolicy(javax.swing.JTabbedPane.SCROLL_TAB_LAYOUT);
        jTabbedPane1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jTabbedPane1.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jTabbedPane1.setPreferredSize(new java.awt.Dimension(810, 450));
        jTabbedPane1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTabbedPane1MouseClicked(evt);
            }
        });

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N

        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel11.setText("1");

        jLabel12.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel12.setText("7");

        jLabel13.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel13.setText("2");

        jLabel14.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel14.setText("3");

        jLabel15.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel15.setText("4");

        jLabel16.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel16.setText("5");

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jButton1.setBackground(new java.awt.Color(51, 51, 255));
        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Đổi Ảnh");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jPanel7.setBackground(new java.awt.Color(255, 51, 51));

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        jLabel8.setText("THÔNG TIN SINH VIÊN");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel8)
                .addContainerGap(23, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jSeparator4.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(jButton1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel16, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(333, Short.MAX_VALUE)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(175, 175, 175))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jButton1)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 385, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(282, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("THÔNG TIN", jPanel6);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jTable1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "MÃ HP", "TÊN HP", "MÃ LỚP", "GIẢNG VIÊN"
            }
        ));
        jTable1.setIntercellSpacing(new java.awt.Dimension(0, 0));
        jTable1.setRowHeight(25);
        jTable1.setSelectionBackground(new java.awt.Color(232, 57, 95));
        jScrollPane1.setViewportView(jTable1);

        jLabel3.setText("CÁC MÔN HỌC");

        jLabel4.setText("LỊCH HỌC");

        jScrollPane3.setViewportBorder(javax.swing.BorderFactory.createCompoundBorder());

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "THỨ", "GIỜ HỌC", "LỚP"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable3.setGridColor(new java.awt.Color(51, 51, 51));
        jTable3.setIntercellSpacing(new java.awt.Dimension(0, 0));
        jTable3.setRowHeight(25);
        jTable3.setSelectionBackground(new java.awt.Color(232, 57, 95));
        jScrollPane3.setViewportView(jTable3);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel3)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 762, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.LEADING))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(289, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("THỜI KHÓA BIỂU", jPanel2);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable4.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Mã Học Phần", "Tên Học Phần", "Số Tín Chỉ", "Tiền/tín"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Long.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable4.setIntercellSpacing(new java.awt.Dimension(0, 0));
        jTable4.setRowHeight(25);
        jTable4.setSelectionBackground(new java.awt.Color(232, 57, 95));
        jTable4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable4MouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(jTable4);

        jPanel3.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 772, 204));

        jLabel2.setText("Tổng tiền: ");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(529, 298, 104, 44));

        jLabel6.setText("jLabel6");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(639, 313, 90, -1));

        jLabel10.setText("Nợ kì trước:");
        jPanel3.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(529, 278, 104, -1));

        jLabel17.setText("jLabel17");
        jPanel3.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(633, 278, 90, -1));

        jLabel18.setText("Đã đóng");
        jPanel3.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(529, 348, 56, -1));

        jLabel19.setText("jLabel19");
        jPanel3.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(639, 348, 90, -1));

        jSeparator6.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator6.setForeground(new java.awt.Color(0, 0, 0));
        jPanel3.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(514, 373, 248, 10));

        jLabel20.setText("Còn phải đóng:");
        jPanel3.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(533, 389, 89, -1));

        jLabel21.setText("jLabel21");
        jPanel3.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 389, 110, -1));

        jTabbedPane1.addTab("HỌC PHÍ", jPanel3);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        jTable5.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5"
            }
        ));
        jTable5.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        jTable5.setIntercellSpacing(new java.awt.Dimension(0, 0));
        jTable5.setRowHeight(25);
        jTable5.setSelectionBackground(new java.awt.Color(232, 57, 95));
        jTable5.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jTable5.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jTable5.setShowVerticalLines(false);
        jScrollPane5.setViewportView(jTable5);

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setSelected(true);
        jRadioButton1.setText("Kì hiện tại");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setText("Lịch sử học tập");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });

        buttonGroup2.add(jRadioButton4);
        jRadioButton4.setText("Điểm QT");

        buttonGroup2.add(jRadioButton5);
        jRadioButton5.setText("Điểm CK");
        jRadioButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton5ActionPerformed(evt);
            }
        });

        jButton3.setText("Gửi");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(183, 183, 183)
                .addComponent(jRadioButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(jRadioButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(270, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(125, 125, 125))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton5)
                    .addComponent(jRadioButton4))
                .addGap(12, 12, 12)
                .addComponent(jButton3)
                .addGap(99, 99, 99))
        );

        buttonGroup1.add(jRadioButton3);
        jRadioButton3.setText("Tổng kết");
        jRadioButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton3ActionPerformed(evt);
            }
        });

        jButton2.setText("Phúc khảo");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton6);
        jRadioButton6.setText("Học phần còn nợ");
        jRadioButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton6ActionPerformed(evt);
            }
        });

        jLabel24.setText("jLabel24");

        jLabel23.setText("jLabel23");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton2)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jRadioButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)
                        .addComponent(jRadioButton2)
                        .addGap(45, 45, 45)
                        .addComponent(jRadioButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jRadioButton6))
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 668, Short.MAX_VALUE)
                    .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(39, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51)
                .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(132, 132, 132))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton1)
                    .addComponent(jRadioButton2)
                    .addComponent(jRadioButton3)
                    .addComponent(jRadioButton6))
                .addGap(27, 27, 27)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(jLabel23))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2)
                .addGap(41, 41, 41)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(146, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("KẾT QUẢ HỌC TẬP", jPanel4);

        jPanel9.setBackground(new java.awt.Color(255, 255, 255));
        jPanel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel9MouseClicked(evt);
            }
        });

        jTable6.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable6.setRowHeight(25);
        jTable6.setSelectionBackground(new java.awt.Color(204, 204, 255));
        jTable6.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jTable6.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane8.setViewportView(jTable6);

        buttonGroup3.add(jRadioButton7);
        jRadioButton7.setSelected(true);
        jRadioButton7.setText("Đơn đã phê duyệt");
        jRadioButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton7ActionPerformed(evt);
            }
        });

        buttonGroup3.add(jRadioButton8);
        jRadioButton8.setText("Đơn chưa phê duyệt");
        jRadioButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton8ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addContainerGap(104, Short.MAX_VALUE)
                .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 575, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(93, 93, 93))
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(137, 137, 137)
                .addComponent(jRadioButton7)
                .addGap(39, 39, 39)
                .addComponent(jRadioButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton7)
                    .addComponent(jRadioButton8))
                .addGap(33, 33, 33)
                .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(189, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("THÔNG BÁO", jPanel9);

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jSeparator5.setBackground(new java.awt.Color(204, 204, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(0, 74, Short.MAX_VALUE)
                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 844, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 779, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(55, 55, 55))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 710, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(98, 98, 98))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 745, Short.MAX_VALUE)
                .addContainerGap())
        );

        jScrollPane6.setViewportView(jPanel1);

        getContentPane().add(jScrollPane6);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTabbedPane1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTabbedPane1MouseClicked

        lopInf = new LopInf();
        IO w = new IO();
        SinhVien sv = new SinhVien();
        sv1=sv;
        w.readFileSV(sv);
        sm=sv.getIDSV();
        tabOne Tab_one = new tabOne(sv);
        TableOne TBOne = new TableOne(sv);
        Table3 TB3 = new Table3(sv);
        Table4 TB4 = new Table4(sv);
        Table5 TB5 = new Table5(sv);
        table tb = new table();
        jButton2.setVisible(false);
        jPanel8.setVisible(false);
         jLabel23.setVisible(false);
        jLabel24.setVisible(false);
         Table_6 tab = new Table_6();
    }//GEN-LAST:event_jTabbedPane1MouseClicked

    private void jTable4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable4MouseClicked

        // TODO add your handling code here:
    }//GEN-LAST:event_jTable4MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        JFileChooser fileCh = new JFileChooser();
        FileNameExtensionFilter igfile = new FileNameExtensionFilter("hinh anh","jpg","png");
        fileCh.setFileFilter(igfile);
        fileCh.setMultiSelectionEnabled(false);
        int x = fileCh.showDialog(this,"Chọn Ảnh");
        if(x==JFileChooser.APPROVE_OPTION)
        {
            File f = fileCh.getSelectedFile();
            jLabel5.setIcon(new ImageIcon(new ImageIcon(f.getAbsolutePath()).getImage().getScaledInstance(jLabel5.getWidth(), jLabel5.getHeight(), Image.SCALE_SMOOTH)));
            
            user = new User();
            user.updateAnhSV( f.getAbsolutePath(),sm);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
        ChonHT =1; 
        Table5 TB5 = new Table5(sv1);
        jButton2.setVisible(true);
        jLabel23.setVisible(false);
        jLabel24.setVisible(false);
        
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        // TODO add your handling code here:
         ChonHT =2; 
        Table5 TB5 = new Table5(sv1);
        jButton2.setVisible(false);
        jPanel8.setVisible(false);
        jLabel23.setVisible(false);
        jLabel24.setVisible(false);
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void jRadioButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton3ActionPerformed
        // TODO add your handling code here:
        ChonHT =3;
        Table5 TB5 = new Table5(sv1);
        jButton2.setVisible(false);
        jPanel8.setVisible(false);
        jLabel23.setVisible(true);
        jLabel24.setVisible(true);
    }//GEN-LAST:event_jRadioButton3ActionPerformed

    private void jRadioButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton6ActionPerformed
        // TODO add your handling code here:
         ChonHT =4;
        Table5 TB5 = new Table5(sv1);
        jButton2.setVisible(false);
        jPanel8.setVisible(false);
        jLabel23.setVisible(true);
        jLabel24.setVisible(true);
    }//GEN-LAST:event_jRadioButton6ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        if(BIEN==1) {jPanel8.setVisible(false); BIEN=0;}
        else 
        {
            BIEN=1;
            
        
         if(jTable5.getSelectedRowCount()>0)
        {
           
           int x = jTable5.getSelectedRow();
             jPanel8.setVisible(true);
             
             pd.setIdlop(jTable5.getValueAt(x, 0).toString());
            
            pd.setTrangthaiduyet("C");
            b=x;
        }
        else
        {
            JFrame frame = new JFrame("JOptionPane showMessageDialog example");
                 JOptionPane.showMessageDialog(frame, "Chưa chọn lớp", "Báo lỗi", JOptionPane.INFORMATION_MESSAGE);
        }
        }
            
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        
        BIEN = 0;
       if(jRadioButton4.isSelected() || jRadioButton5.isSelected() )
       {jPanel8.setVisible(false);
          if(jRadioButton4.isSelected())
          {
              pd.setLoaidiem("gk");
              
         int k = lopInf.Ktra(pd.getIdlop(),pd.getIdsv(),1);
              if(k==0)
              {
                  if(lopInf.KtraDon(pd)==0)
             
                  { SqlDuyet duyet = new SqlDuyet();
            pd.setDiem_truocPK(Float.parseFloat(jTable5.getValueAt(b, 3).toString()));
             duyet.GuidonPK(pd);
            buttonGroup2.clearSelection();
        JFrame frame = new JFrame("JOptionPane showMessageDialog example");
                 JOptionPane.showMessageDialog(frame, "Đã gửi đơn cho giáo viên lớp", "Thông Báo", JOptionPane.INFORMATION_MESSAGE);}
                  else
              {
                   JFrame frame = new JFrame("JOptionPane showMessageDialog example");
                 JOptionPane.showMessageDialog(frame, "Da phuc khao roi", "Thông Báo", JOptionPane.INFORMATION_MESSAGE);
              }
              }
              else
              {
                   JFrame frame = new JFrame("JOptionPane showMessageDialog example");
                 JOptionPane.showMessageDialog(frame, "chưa có điểm, không thể phúc khảo", "Thông Báo", JOptionPane.INFORMATION_MESSAGE);
              }
          }
            else
          {
              
              int k = lopInf.Ktra(pd.getIdlop(),pd.getIdsv(),2);
              if(k==0)
              {
             if(lopInf.KtraDon(pd)==0)
             {
           SqlDuyet duyet = new SqlDuyet();
            pd.setDiem_truocPK(Float.parseFloat(jTable5.getValueAt(b, 4).toString()));
            duyet.GuidonPK(pd);
            buttonGroup2.clearSelection();
        JFrame frame = new JFrame("JOptionPane showMessageDialog example");
                 JOptionPane.showMessageDialog(frame, "Đã gửi đơn cho giáo viên lớp", "Thông Báo", JOptionPane.INFORMATION_MESSAGE);}
             else
             {
                 JFrame frame = new JFrame("JOptionPane showMessageDialog example");
                 JOptionPane.showMessageDialog(frame, "Da phuc khao roi", "Thông Báo", JOptionPane.INFORMATION_MESSAGE);
             }
              }
              else
              {
                  JFrame frame = new JFrame("JOptionPane showMessageDialog example");
                 JOptionPane.showMessageDialog(frame, "chưa có điểm, không thể phúc khảo", "Thông Báo", JOptionPane.INFORMATION_MESSAGE);
              }
          }
           
            
       }
       else
       {
            
            JFrame frame = new JFrame("JOptionPane showMessageDialog example");
                 JOptionPane.showMessageDialog(frame, "Chưa chọn đối tương phúc khảo", "Thông Báo", JOptionPane.INFORMATION_MESSAGE);
       }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jRadioButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton5ActionPerformed

    private void jPanel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel9MouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jPanel9MouseClicked

    private void jRadioButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton7ActionPerformed
        // TODO add your handling code here:
      //  Table_6 tb = new Table_6();
       BIEN2 =0;
        Table_6 tb = new Table_6();
    }//GEN-LAST:event_jRadioButton7ActionPerformed

    private void jRadioButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton8ActionPerformed
        // TODO add your handling code here:
        BIEN2 =1;
        Table_6 tb = new Table_6();
    }//GEN-LAST:event_jRadioButton8ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SVInf.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SVInf.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SVInf.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SVInf.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SVInf().setVisible(true);
            }
        });
    }
    public static class HeaderColor extends DefaultTableCellRenderer
    {
        public HeaderColor()
        {
            setOpaque(true);
        }
        public Component getTableCellRendererComponent(JTable mytable, Object value,boolean selected,boolean focused,int row,int column)
        {
            super.getTableCellRendererComponent(mytable, value, selected, focused, row, column);
            setBackground(new java.awt.Color(32,136,203));
            setForeground(new java.awt.Color(255,255,255));
            return this;
        }
        
    }
    public class table
    {
        public table()
        {
        jTable6.getTableHeader().setDefaultRenderer(new HeaderColor());
        jTable5.getTableHeader().setDefaultRenderer(new HeaderColor());
        jTable4.getTableHeader().setDefaultRenderer(new HeaderColor());
        jTable3.getTableHeader().setDefaultRenderer(new HeaderColor());
        jTable1.getTableHeader().setDefaultRenderer(new HeaderColor());
         JTableHeader tb3 = jTable3.getTableHeader();
        ((DefaultTableCellRenderer)tb3.getDefaultRenderer()).setHorizontalAlignment(JLabel.CENTER);
         JTableHeader tb4 = jTable4.getTableHeader();
        ((DefaultTableCellRenderer)tb4.getDefaultRenderer()).setHorizontalAlignment(JLabel.CENTER);
         JTableHeader tb5 = jTable5.getTableHeader();
        ((DefaultTableCellRenderer)tb5.getDefaultRenderer()).setHorizontalAlignment(JLabel.CENTER);
        
        JTableHeader tb6 = jTable6.getTableHeader();
        ((DefaultTableCellRenderer)tb6.getDefaultRenderer()).setHorizontalAlignment(JLabel.CENTER);
        }
    }
    public class tabOne
    {
        public tabOne(SinhVien sv)
        {
        String gt = new String();
        User us = new User();
        us.getInfOne(sv);
        ImageIcon icon = new ImageIcon("src/Anhdd/logo.png");
        Image img = icon.getImage();
        Image imgScale = img.getScaledInstance(jLabel7.getWidth(), jLabel7.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon scaleIcon = new ImageIcon(imgScale);
        jLabel7.setIcon(scaleIcon);
        //jLabel7.setIcon(new ImageIcon(new ImageIcon("src/Anhdd/logo.png").getImage().getScaledInstance(600, 100, Image.SCALE_DEFAULT)));
        jLabel11.setText("Họ và tên : "+sv.getName());
        jLabel12.setText("Mã số sinh viên: "+sv.getIDSV());
        jLabel13.setText("Ngày sinh: "+sv.getNgaysinh());
        if(sv.getGioiTinh()) gt = "Nam";
        else gt = "Nữ";
        jLabel14.setText("Giới tính: "+gt);
        jLabel15.setText("Khoa đang theo học: "+sv.getMaKhoa());
        jLabel16.setText("Địa chỉ hiện tại: "+sv.getDiaChi());
        jLabel9.setText("Email liên hệ: "+sv.getEmail());
        ImageIcon iconA = new ImageIcon(sv.getAnh());
        Image img2 = iconA.getImage();
        Image imgScale2 = img2.getScaledInstance(jLabel5.getWidth(), jLabel5.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon scaleIcon2 = new ImageIcon(imgScale2);
        jLabel5.setIcon(scaleIcon2);
        }
    }
    public class TableOne
    {
        public TableOne(SinhVien sv)
        {
             defaultb = new DefaultTableModel()
                {
                    @Override
    public boolean isCellEditable(int row, int column) {
       //all cells false
       return false;
    }
         
             };
        jTable1.setModel(defaultb);
        defaultb.addColumn("Mã HP");
        defaultb.addColumn("Tên HP");
        defaultb.addColumn("Mã Lớp");
        defaultb.addColumn("Giảng Viên");
        List<ThongTinLop> mclass= lopInf.getClassInf(sv.getIDSV());
        for(ThongTinLop tt : mclass)
        {
            defaultb.addRow(new Object[]{tt.getMaHP(),tt.getTenHP(),tt.getIDLop(),tt.getNameGV() });
            
        }
        }
    }
    public class Table3
    {
        public Table3(SinhVien sv)
        {
            
            defaultb2 = new DefaultTableModel()
                {
                    @Override
    public boolean isCellEditable(int row, int column) {
       //all cells false
       return false;
    }
                };
        jTable3.setModel(defaultb2);
        defaultb2.addColumn("Thứ" );
        defaultb2.addColumn("Thời gian");
        defaultb2.addColumn("Mã Lớp");
        List<ThongTinLop> mclass2= lopInf.getClassInfNgay(sv.getIDSV());
        for(ThongTinLop tt : mclass2)
        {
            String st = new String();
            st =  (tt.getGioMD()).toString()+" - "+ (tt.getGioKT()).toString();
            defaultb2.addRow(new Object[]{tt.getThu(),st,tt.getIDLop() });
            
        }
        DefaultTableCellRenderer rightRenderer = new DefaultTableCellRenderer();
        rightRenderer.setHorizontalAlignment(SwingConstants.CENTER);
 
        TableModel tableModel = jTable3.getModel();
 
        for (int columnIndex = 0; columnIndex < tableModel.getColumnCount(); columnIndex++)
        {
            jTable3.getColumnModel().getColumn(columnIndex).setCellRenderer(rightRenderer);
        }
        }
    }
    public class Table4
    {
        public Table4(SinhVien sv)
        {
            defaultb3 = new DefaultTableModel()
                {
                    @Override
    public boolean isCellEditable(int row, int column) {
       //all cells false
       return false;
    }
                };
        jTable4.setModel(defaultb3);
        defaultb3.addColumn("Mã Học Phần" );
        defaultb3.addColumn("Tên Học Phần");
        defaultb3.addColumn("Số Tín Chỉ");
        defaultb3.addColumn("Tiền/tín(VND)");
        defaultb3.addColumn("Tổng(VND)");
         List<ThongTinLop> mclass3= lopInf.HocPhi(sv.getIDSV());
        for(ThongTinLop tt : mclass3)
        {
           // String st = new String();
            defaultb3.addRow(new Object[]{tt.getMaHP(),tt.getTenHP(),tt.getSoTC(),tt.getTien(),tt.getTong()});
            
        }
        
        DefaultTableCellRenderer rightRenderer2 = new DefaultTableCellRenderer();
        rightRenderer2.setHorizontalAlignment(SwingConstants.CENTER);
        jTable4.getColumnModel().getColumn(2).setCellRenderer(rightRenderer2);
        jTable4.getColumnModel().getColumn(3).setCellRenderer(rightRenderer2);
        jTable4.getColumnModel().getColumn(4).setCellRenderer(rightRenderer2);
        lopInf.TongHP(sv);
        jLabel6.setText(sv.getTonghp()+ " VND");
        jLabel17.setText(sv.getDuno()+ " VND");
        jLabel19.setText(sv.getDadong()+ " VND");
        jLabel21.setText(sv.getDuno()+sv.getTonghp()-sv.getDadong()+ " VND");
        }
    }
    public class Table5
    {
        public Table5(SinhVien sv)
        {
            if(ChonHT==1)
            {
             defaultb4 = new DefaultTableModel()
                {
                    @Override
    public boolean isCellEditable(int row, int column) {
       return false;
    }};
            jTable5.setModel(defaultb4);
            defaultb4.addColumn("Mã lớp");
            defaultb4.addColumn("Tên học phần");
            defaultb4.addColumn("Hệ số QT");
            defaultb4.addColumn("Điểm giữa kì");
            defaultb4.addColumn("Điểm cuối kì");
            defaultb4.addColumn("Điểm tổng kết");
            
            List<DiemSV> mclass4 = lopInf.diemsv(sv.getIDSV());
        for(DiemSV tt : mclass4)
        {
            String ck, gk;
            if(tt.getDiemCK()==-1) ck=""; else ck = ""+tt.getDiemCK();
            if(tt.getDiemGK()==-1) gk ="";else gk = ""+tt.getDiemGK();
            if(tt.getDiemCK()!= -1 && tt.getDiemGK()!=-1)
            {
                float dtk = (float) ((tt.getDiemCK())*(1-tt.getTrongsodiemqt())+(tt.getDiemGK()) *tt.getTrongsodiemqt());
                defaultb4.addRow(new Object[]{tt.getIDLop(),tt.getTenHP(),tt.getTrongsodiemqt(),tt.getDiemGK(),tt.getDiemCK(),dtk});
            }
            else
            defaultb4.addRow(new Object[]{tt.getIDLop(),tt.getTenHP(),tt.getTrongsodiemqt(),gk,ck,""});
            
        }
       
        }
           
            else if(ChonHT ==2)
            {
               defaultb4 = new DefaultTableModel()
                {
                    @Override
    public boolean isCellEditable(int row, int column) {
       return false;
    }};
            jTable5.setModel(defaultb4);
            defaultb4.addColumn("Năm học");
            defaultb4.addColumn("Kì học");
            defaultb4.addColumn("Mã HP");
            defaultb4.addColumn("Số TC");
            defaultb4.addColumn("Tên HP");
            defaultb4.addColumn("Điểm QT");
            defaultb4.addColumn("Điểm CK");
            defaultb4.addColumn("Điểm HP");
            defaultb4.addColumn("Điểm chữ");
            
            List<LichSuHT> mclass4 = lopInf.ThanhTich(sv1.getIDSV());
        for(LichSuHT tt : mclass4)
        {
            String ck, gk,hk;
            if(tt.getDiemCK()==-1) ck=""; else ck = ""+tt.getDiemCK();
            if(tt.getDiemQT()==-1) gk ="";else gk = ""+tt.getDiemQT();
            if(tt.getDiemhp()==-1) hk ="";else hk = ""+tt.getDiemhp();
            if(tt.getDiemCK()!= -1 && tt.getDiemQT()!=-1 && tt.getDiemhp()!=-1)
            {
                
                defaultb4.addRow(new Object[]{tt.getNamhoc(),tt.getKihoc(),tt.getMahp(),tt.getSOTC(),tt.getTenHP(),tt.getDiemQT(),tt.getDiemCK(),tt.getDiemhp(),tt.getDiemchu()});
            }
            else
            defaultb4.addRow(new Object[]{tt.getNamhoc(),tt.getKihoc(),tt.getMahp(),tt.getSOTC(),tt.getTenHP(),gk,ck,hk,tt.getDiemchu()});
            
        }
       
            }
            else if(ChonHT==3)
            {
                defaultb4 = new DefaultTableModel()
                {
                    @Override
    public boolean isCellEditable(int row, int column) {
       return false;
    }};
            jTable5.setModel(defaultb4);
            defaultb4.addColumn("Năm học");
            defaultb4.addColumn("Kì học");
            defaultb4.addColumn("GPA");
            defaultb4.addColumn("CPA");
            
            List<LichSuHT> mclass4 = lopInf.TongKet(sv1.getIDSV());
                    
        for(LichSuHT tt : mclass4)
        {
            
                
                defaultb4.addRow(new Object[]{tt.getNamhoc(),tt.getKihoc(),tt.getTBKi(),tt.getCPA()});
          
            }
        int sotc = lopInf.SoTCQua(sv1.getIDSV());
        jLabel23.setText("Số tín chỉ qua: ");
        jLabel24.setText(sotc+"");
             
        }
            else 
            {
                 defaultb4 = new DefaultTableModel()
                {
                    @Override
    public boolean isCellEditable(int row, int column) {
       return false;
    }};
            jTable5.setModel(defaultb4);
            defaultb4.addColumn("Năm học");
            defaultb4.addColumn("Kì học");
            defaultb4.addColumn("Mã HP");
            defaultb4.addColumn("Tên HP");
            defaultb4.addColumn("Điểm QT");
            defaultb4.addColumn("Điểm CK");
            defaultb4.addColumn("Điểm HP");
            defaultb4.addColumn("Điểm chữ");
            
            List<LichSuHT> mclass4 = lopInf.NoTin(sv1.getIDSV());
        for(LichSuHT tt : mclass4)
        {
            String ck, gk,hk;
            if(tt.getDiemCK()==-1) ck=""; else ck = ""+tt.getDiemCK();
            if(tt.getDiemQT()==-1) gk ="";else gk = ""+tt.getDiemQT();
            if(tt.getDiemhp()==-1) hk ="";else hk = ""+tt.getDiemhp();
            if(tt.getDiemCK()!= -1 && tt.getDiemQT()!=-1 && tt.getDiemhp()!=-1)
            {
                
                defaultb4.addRow(new Object[]{tt.getNamhoc(),tt.getKihoc(),tt.getMahp(),tt.getTenHP(),tt.getDiemQT(),tt.getDiemCK(),tt.getDiemhp(),tt.getDiemchu()});
            }
            else
            defaultb4.addRow(new Object[]{tt.getNamhoc(),tt.getKihoc(),tt.getMahp(),tt.getTenHP(),gk,ck,hk,tt.getDiemchu()});
            
        }
                int sotc = lopInf.SoTCChuaqua(sv1.getIDSV());
        jLabel23.setText("Số tín chỉ chưa qua: ");
        jLabel24.setText(sotc+"");
            }
            DefaultTableCellRenderer rightRenderer3 = new DefaultTableCellRenderer();
        rightRenderer3.setHorizontalAlignment(SwingConstants.CENTER);
 
        TableModel tableModel5 = jTable5.getModel();
 
        for (int columnIndex = 2; columnIndex < tableModel5.getColumnCount(); columnIndex++)
        {
            jTable5.getColumnModel().getColumn(columnIndex).setCellRenderer(rightRenderer3);
        }
    }
    }
    public class Table_6
    {
        
        public Table_6()
        {
           if(BIEN2==1)
           {
             defaultb6 = new DefaultTableModel()
                {
                    @Override
    public boolean isCellEditable(int row, int column) {
       //all cells false
       return false;
    }
                };
             jTable6.setModel(defaultb6);
        defaultb6.addColumn("STT");
        defaultb6.addColumn("Hành động");
        defaultb6.addColumn("loai diem");
        defaultb6.addColumn("diem truoc PK");
        defaultb6.addColumn("Mã lớp");
         SqlDuyet duyet = new SqlDuyet();
         List<DonPK> day= duyet.ThongKeDonSV(sv1.getIDSV());
         int stt=1;
        for(DonPK tt : day)
        {
            String hdong = new String();
           
               hdong = "Phúc khảo ";
                
            defaultb6.addRow(new Object[]{stt,hdong,tt.getLoaidiem(),tt.getDiem_truocPK(),tt.getIdlop()});
            stt++;
            
        }
        
        }
        
        else
        {
            defaultb6 = new DefaultTableModel()
                {
                    @Override
    public boolean isCellEditable(int row, int column) {
       //all cells false
       return false;
    }
                };
             jTable6.setModel(defaultb6);
     jTable6.setModel(defaultb6);
        defaultb6.addColumn("STT");
        defaultb6.addColumn("Hành động");
        defaultb6.addColumn("loai diem");
        defaultb6.addColumn("diem truoc PK");
        defaultb6.addColumn("diem sau PK");
        defaultb6.addColumn("Mã lớp");
         SqlDuyet duyet = new SqlDuyet();
         List<DonPK> day= duyet.ThongKeDonSVDD(sv1.getIDSV());
         int stt=1;
        for(DonPK tt : day)
        {
            String hdong = new String();
           
               hdong = "Phúc khảo ";
                
            defaultb6.addRow(new Object[]{stt,hdong,tt.getLoaidiem(),tt.getDiem_truocPK(),tt.getDiem_sauPK(),tt.getIdlop()});
            stt++;
            
        }
        
        
        }
    }
        }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JRadioButton jRadioButton5;
    private javax.swing.JRadioButton jRadioButton6;
    private javax.swing.JRadioButton jRadioButton7;
    private javax.swing.JRadioButton jRadioButton8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JTable jTable4;
    private javax.swing.JTable jTable5;
    private javax.swing.JTable jTable6;
    // End of variables declaration//GEN-END:variables
}
