/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GiaodienIn;

/**
 *
 * @author ADMIN
 */
import GiaoDien.*;
import IOfile.IO;
import InforSQL.DoiGV;
import InforSQL.DonPK;
import InforSQL.GiangVien;
import InforSQL.PheDuyet;
import InforSQL.ThongTinLop;
import LopInf.LopInf;
import PheDuyet.SqlDuyet;
import User.User;
import java.awt.Component;
import java.awt.Image;
import java.io.File;
import java.time.LocalDateTime;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.ListSelectionModel;
import javax.swing.SwingConstants;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;
import javax.swing.table.TableModel;
import java.sql.Timestamp;
public class GiangVienTruong extends javax.swing.JFrame {

    /**
     * Creates new form GiangVienTruong
     */
     DefaultTableModel defaultb  = new DefaultTableModel(); 
     DefaultTableModel defaultb2 = new DefaultTableModel();
     DefaultTableModel defaultb3 = new DefaultTableModel();
     DefaultTableModel defaultb4 = new DefaultTableModel();
     DefaultTableModel defaultb5 = new DefaultTableModel();
     DefaultTableModel defaultb6 = new DefaultTableModel();
     LopInf lopInf;
     GiangVien gv = new GiangVien();
     User user;
     String sm = new String();
     IO w = new IO();
     int dd = 0;
     int LuaChon=0;
     int ChonKN =0;
     String lop_change= new String();
    public GiangVienTruong() {
        initComponents();
        this.setLocationRelativeTo(null);
        jPanel8.setVisible(false);
        jButton5.setVisible(false);
        lopInf = new LopInf();
        w.readFileGV(gv);
        sm = gv.getIDGV();
        tabOne Tab_one = new tabOne(gv);
        TableOne TBOne = new TableOne(gv);
        Table2 TB2 = new Table2(gv);
        Table3 TB3 = new Table3(gv);
        table4 TB4 = new table4();
        table tb = new table();
        table6 tb6 = new table6();
        jRadioButton3.setSelected(true);
        jButton7.setVisible(false);
        jButton4.setVisible(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jScrollPane6 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel6 = new javax.swing.JPanel();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel10 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jSeparator2 = new javax.swing.JSeparator();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable4 = new javax.swing.JTable();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jButton5 = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTable5 = new javax.swing.JTable();
        jScrollPane7 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButton6 = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jScrollPane8 = new javax.swing.JScrollPane();
        jTable6 = new javax.swing.JTable();
        jRadioButton5 = new javax.swing.JRadioButton();
        jRadioButton6 = new javax.swing.JRadioButton();
        jButton7 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jTabbedPane1.setBackground(new java.awt.Color(255, 255, 255));
        jTabbedPane1.setBorder(new javax.swing.border.MatteBorder(null));
        jTabbedPane1.setForeground(new java.awt.Color(255, 0, 0));
        jTabbedPane1.setTabLayoutPolicy(javax.swing.JTabbedPane.SCROLL_TAB_LAYOUT);
        jTabbedPane1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jTabbedPane1.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jTabbedPane1.setPreferredSize(new java.awt.Dimension(810, 450));
        jTabbedPane1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTabbedPane1MouseClicked(evt);
            }
        });

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N

        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel11.setText("1");

        jLabel12.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel12.setText("7");

        jLabel13.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel13.setText("2");

        jLabel14.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel14.setText("3");

        jLabel15.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel15.setText("4");

        jLabel16.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel16.setText("5");

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jButton1.setBackground(new java.awt.Color(51, 51, 255));
        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Đổi Ảnh");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jPanel7.setBackground(new java.awt.Color(51, 51, 255));
        jPanel7.setForeground(new java.awt.Color(255, 204, 204));

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("THÔNG TIN GIẢNG VIÊN");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel8)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jSeparator4.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jLabel10.setBackground(new java.awt.Color(255, 255, 255));
        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(jButton1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel16, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(570, Short.MAX_VALUE)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(175, 175, 175))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jButton1)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 385, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(184, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("THÔNG TIN", jPanel6);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jTable1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "MÃ HP", "TÊN HP", "MÃ LỚP"
            }
        ));
        jTable1.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        jTable1.setIntercellSpacing(new java.awt.Dimension(0, 0));
        jTable1.setRowHeight(25);
        jTable1.setSelectionBackground(new java.awt.Color(153, 153, 255));
        jTable1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jTable1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(jTable1);

        jLabel3.setText("CÁC MÔN DẠY");

        jLabel4.setText("LỊCH DẠY");

        jScrollPane3.setViewportBorder(javax.swing.BorderFactory.createCompoundBorder());

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "THỨ", "GIỜ ", "LỚP"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable2.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        jTable2.setGridColor(new java.awt.Color(51, 51, 51));
        jTable2.setIntercellSpacing(new java.awt.Dimension(0, 0));
        jTable2.setRowHeight(25);
        jTable2.setSelectionBackground(new java.awt.Color(153, 153, 255));
        jTable2.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jTable2.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane3.setViewportView(jTable2);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel3)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 1005, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.LEADING))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(191, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("THỜI KHÓA BIỂU", jPanel2);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jTable3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Mã Học Phần", "Tên Học Phần", "Mã Lớp"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable3.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        jTable3.setGridColor(new java.awt.Color(204, 204, 204));
        jTable3.setIntercellSpacing(new java.awt.Dimension(0, 0));
        jTable3.setRowHeight(25);
        jTable3.setSelectionBackground(new java.awt.Color(153, 153, 255));
        jTable3.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jTable3.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jTable3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable3MouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(jTable3);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel1.setText("CÁC LỚP ĐANG DẠY");

        jLabel2.setText("Nhập mã học phần(hoặc mã lớp)");

        jButton2.setBackground(new java.awt.Color(255, 255, 0));
        jButton2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 0, 51));
        jButton2.setText("Tìm kiếm");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(204, 255, 255));
        jButton3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 0, 255));
        jButton3.setText("MỞ LỚP");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1015, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(51, 51, 51)
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel1))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel6)
                        .addGap(99, 99, 99))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton2))
                        .addGap(23, 23, 23)
                        .addComponent(jLabel1)
                        .addGap(30, 30, 30)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButton3))
                .addGap(73, 73, 73)
                .addComponent(jLabel6)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("QUẢN LÝ LỚP", jPanel3);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable4.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable4.setRowHeight(25);
        jTable4.setSelectionBackground(new java.awt.Color(204, 204, 255));
        jScrollPane2.setViewportView(jTable4);

        jPanel4.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 65, 570, 350));

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setText("Lớp");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });
        jPanel4.add(jRadioButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 11, 68, -1));

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setText("Giảng viên");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });
        jPanel4.add(jRadioButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(111, 11, 93, -1));

        jButton5.setText("Đổi giảng viên");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(232, 11, -1, -1));

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));

        jTable5.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane5.setViewportView(jTable5);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane7.setViewportView(jTextArea1);

        jButton6.setText("Gửi ");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jLabel18.setText("Các giảng viên có thể thay thế được");

        jLabel20.setText("Lí do");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                        .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                        .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(42, 42, 42))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 371, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26))))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(jLabel20))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(30, 30, 30)
                .addComponent(jButton6)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        jPanel4.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 10, 380, -1));

        jTabbedPane1.addTab("QUẢN LÝ KHOA", jPanel4);

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        buttonGroup2.add(jRadioButton3);
        jRadioButton3.setText("Chưa Phê duyệt");
        jRadioButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton3ActionPerformed(evt);
            }
        });

        buttonGroup2.add(jRadioButton4);
        jRadioButton4.setText("Đơn được phê duyệt");
        jRadioButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton4ActionPerformed(evt);
            }
        });

        jTable6.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable6.setRowHeight(25);
        jTable6.setSelectionBackground(new java.awt.Color(204, 204, 255));
        jTable6.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jTable6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable6MouseClicked(evt);
            }
        });
        jScrollPane8.setViewportView(jTable6);

        buttonGroup2.add(jRadioButton5);
        jRadioButton5.setText("Đơn cần phê duyệt");
        jRadioButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton5ActionPerformed(evt);
            }
        });

        buttonGroup2.add(jRadioButton6);
        jRadioButton6.setText("Đơn đã phê duyệt");
        jRadioButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton6ActionPerformed(evt);
            }
        });

        jButton7.setText("Đồng ý");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton4.setText("Không đồng ý");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(160, 160, 160)
                        .addComponent(jRadioButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(54, 54, 54)
                        .addComponent(jRadioButton4)
                        .addGap(39, 39, 39)
                        .addComponent(jRadioButton5)
                        .addGap(32, 32, 32)
                        .addComponent(jRadioButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(111, 111, 111)
                        .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 684, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(220, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(jButton4)
                .addGap(277, 277, 277))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton3)
                    .addComponent(jRadioButton4)
                    .addComponent(jRadioButton5)
                    .addComponent(jRadioButton6))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton7)
                    .addComponent(jButton4))
                .addContainerGap(194, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("KIẾN NGHỊ", jPanel5);

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jSeparator5.setBackground(new java.awt.Color(204, 204, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(124, 124, 124)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 710, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(52, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 844, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(62, 62, 62))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1022, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 647, Short.MAX_VALUE)
                .addContainerGap())
        );

        jScrollPane6.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 1129, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 681, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTabbedPane1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTabbedPane1MouseClicked

    }//GEN-LAST:event_jTabbedPane1MouseClicked

    private void jTable3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable3MouseClicked

        // TODO add your handling code here:
    }//GEN-LAST:event_jTable3MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        JFileChooser fileCh = new JFileChooser();
        FileNameExtensionFilter igfile = new FileNameExtensionFilter("hinh anh","jpg","png");
        fileCh.setFileFilter(igfile);
        fileCh.setMultiSelectionEnabled(false);
        int x = fileCh.showDialog(this,"Chọn Ảnh");
        if(x==JFileChooser.APPROVE_OPTION)
        {
             File f = fileCh.getSelectedFile();
            jLabel5.setIcon(new ImageIcon(new ImageIcon(f.getAbsolutePath()).getImage().getScaledInstance(jLabel5.getWidth(), jLabel5.getHeight(), Image.SCALE_SMOOTH)));
            
            user = new User();
            user.updateAnhGV( f.getAbsolutePath(),sm);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       
                    String str = new String();
                    str = jTextField1.getText();
                    defaultb3.setRowCount(0);
                    lopInf = new LopInf();
                    int m=0;
        List<ThongTinLop> mlop= lopInf.getHPGV2(gv.getIDGV(),str);
        for(ThongTinLop tt : mlop)
        {
            defaultb3.addRow(new Object[]{tt.getMaHP(),tt.getTenHP(),tt.getIDLop()});
            m++;
            
        }
        
           jLabel9.setText("Số kết quả tìm thấy : "+m);

                    
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        if(jTable3.getSelectedRowCount()>0)
        {
        
             int x = jTable3.getSelectedRow();
             String code = String.valueOf(jTable3.getValueAt(x, 2));
             w.writeFileQL(code);
             new QuanLop().setVisible(true);
        }
        else
        {
            JFrame frame = new JFrame("JOptionPane showMessageDialog example");
                 JOptionPane.showMessageDialog(frame, "Chưa chọn lớp", "Báo lỗi", JOptionPane.INFORMATION_MESSAGE);
        }
            
       
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
        
         LuaChon=0;
         table4 TB4 = new table4();
         jButton5.setVisible(true);
         jPanel8.setVisible(false);
        
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        // TODO add your handling code here:
        
        LuaChon=1;
        table4 TB4 = new table4();
        jButton5.setVisible(false);
        jPanel8.setVisible(false);
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        if(jTable4.getSelectedRowCount()>0)
        {
        
             int x = jTable4.getSelectedRow();
             String code = String.valueOf(jTable4.getValueAt(x, 2));
             SqlDuyet dqld = new SqlDuyet();
             if(dqld.HanChe(code)==0)
             {
             
             jPanel8.setVisible(true);
          
             defaultb5 = new DefaultTableModel()
                {
                    @Override
    public boolean isCellEditable(int row, int column) {
       //all cells false
       return false;
    }
                };
             jTable5.setModel(defaultb5);
             defaultb5.addColumn("MSGV");
             defaultb5.addColumn("Họ Tên");
             defaultb5.addColumn("Ngày sinh");
             defaultb5.addColumn("Giới tính");
             ThongTinLop ttin = new ThongTinLop();
             ttin.setIDLop(code);
             
             lop_change = code;
             user = new User();
            List<GiangVien> listGV = user.GvThayThe(ttin,gv.getMaKhoa());
        for(GiangVien tt : listGV)
        {
            String gt;
            if(tt.getGioiTinh()) gt = "Nam";
              else gt = "Nữ";
             defaultb5.addRow(new Object[]{tt.getIDGV(),tt.getNameGV(),tt.getNgaysinh(),gt});
          
            
        }
             }
             else
             {
                  JFrame frame = new JFrame("JOptionPane showMessageDialog example");
                 JOptionPane.showMessageDialog(frame, "Đơn đổi giảng viên lớp này chưa được xác nhận", "Báo lỗi", JOptionPane.INFORMATION_MESSAGE);
             }
             
             
            
        }
        else
        {
            JFrame frame = new JFrame("JOptionPane showMessageDialog example");
                 JOptionPane.showMessageDialog(frame, "Chưa chọn lớp", "Báo lỗi", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
         if(jTable5.getSelectedRowCount()>0)
        {
        
            
            int x = jTable5.getSelectedRow();
            DoiGV pd = new DoiGV ();
            LocalDateTime now = LocalDateTime.now();
            pd.setThoigiangui(Timestamp.valueOf(now));
            pd.setLido(jTextArea1.getText());
            pd.setIdlop(lop_change);
            pd.setDongy("C");
            pd.setIdgv(Integer.parseInt(jTable5.getValueAt(x, 0).toString()));
            SqlDuyet duyet = new SqlDuyet();
            duyet.GuiDon(pd);
            jPanel8.setVisible(false);
            JFrame frame = new JFrame("JOptionPane showMessageDialog example");
                 JOptionPane.showMessageDialog(frame, "Đã gửi đơn cho quản trị viên", "Thông Báo", JOptionPane.INFORMATION_MESSAGE);
        }
        else
        {
            JFrame frame = new JFrame("JOptionPane showMessageDialog example");
                 JOptionPane.showMessageDialog(frame, "Chưa chọn giảng viên thay thế", "Báo lỗi", JOptionPane.INFORMATION_MESSAGE);
        }
        
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jRadioButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton3ActionPerformed
        // TODO add your handling code here:
        jButton7.setVisible(false);
        jButton4.setVisible(false);
        ChonKN = 0;
        table6 tb6 = new table6();
    }//GEN-LAST:event_jRadioButton3ActionPerformed

    private void jTable6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable6MouseClicked
        // TODO add your handling code here:
      
    }//GEN-LAST:event_jTable6MouseClicked

    private void jRadioButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton4ActionPerformed
        // TODO add your handling code here:
        jButton7.setVisible(false);
        jButton4.setVisible(false);
         ChonKN = 1;
        table6 tb6 = new table6();
    }//GEN-LAST:event_jRadioButton4ActionPerformed

    private void jRadioButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton5ActionPerformed
        // TODO add your handling code here:
        jButton7.setVisible(true);
        jButton4.setVisible(true);
          ChonKN = 2;
        table6 tb6 = new table6();
    }//GEN-LAST:event_jRadioButton5ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        if(jTable6.getSelectedRow()>=0)
        {
             int x = jTable6.getSelectedRow();
            DonPK pd = new DonPK();
            
            pd.setDiem_truocPK(Float.parseFloat(jTable6.getValueAt(x, 3).toString()));
             pd.setLoaidiem(jTable6.getValueAt(x, 2).toString());
             if(pd.getLoaidiem().equals("gk ") ) jButton7.setText("Yeee");
             
          
            pd.setIdsv(Integer.parseInt(jTable6.getValueAt(x, 5).toString()));
            pd.setIdlop(jTable6.getValueAt(x, 4).toString());
           
            pd.setTrangthaiduyet("Y");
            lopInf.DiemPk(pd);
            SqlDuyet s = new SqlDuyet();
            
            s.DuyetDonPK(pd);
            table6 tb = new table6();
            
           
            
        }
       
        
      
        
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jRadioButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton6ActionPerformed
        // TODO add your handling code here:
        jButton7.setVisible(false);
        jButton4.setVisible(false);
        ChonKN=3;
        table6 tb = new table6();
        
    }//GEN-LAST:event_jRadioButton6ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        if(jTable6.getSelectedRow()>=0)
        {
            int x = jTable6.getSelectedRow();
            DonPK pd = new DonPK();
            pd.setDiem_truocPK(Float.parseFloat(jTable6.getValueAt(x, 3).toString()));
            pd.setDiem_sauPK(pd.getDiem_truocPK());
            pd.setIdsv(Integer.parseInt(jTable6.getValueAt(x, 5).toString()));
            pd.setIdlop(jTable6.getValueAt(x, 4).toString());
            pd.setLoaidiem(jTable6.getValueAt(x, 2).toString());
            pd.setTrangthaiduyet("N");
            SqlDuyet s = new SqlDuyet();
            s.DuyetDonPK(pd);
            table6 tb = new table6();
            
           
            
        }
     
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GiangVienTruong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GiangVienTruong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GiangVienTruong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GiangVienTruong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GiangVienTruong().setVisible(true);
            }
        });
    }
   public class tabOne
   {
       public tabOne(GiangVien gv)
       {
        String gt = new String();
        User us = new User();
        us.getInfOneGV(gv);
        ImageIcon icon = new ImageIcon("src/Anhdd/logo.png");
        Image img = icon.getImage();
        Image imgScale = img.getScaledInstance(jLabel7.getWidth(), jLabel7.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon scaleIcon = new ImageIcon(imgScale);
        jLabel7.setIcon(scaleIcon);
        //jLabel7.setIcon(new ImageIcon(new ImageIcon("src/Anhdd/logo.png").getImage().getScaledInstance(600, 100, Image.SCALE_DEFAULT)));
        jLabel11.setText("Họ và tên giảng viên : "+gv.getNameGV());
        jLabel12.setText("Mã số giảng viên: "+gv.getIDGV());
        jLabel13.setText("Ngày Sinh: "+gv.getNgaysinh());
        if(gv.getGioiTinh()) gt = "Nam";
        else gt = "Nữ";
        jLabel14.setText("Giới tính: "+gt);
        jLabel15.setText("Khoa đang dạy: "+gv.getMaKhoa());
        jLabel16.setText("Địa chỉ hiện tại: "+gv.getDiaChi());
        jLabel10.setText("Email liên hệ: "+gv.getEmail());
        ImageIcon iconA = new ImageIcon(gv.getAnh());
        Image img2 = iconA.getImage();
        Image imgScale2 = img2.getScaledInstance(jLabel5.getWidth(), jLabel5.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon scaleIcon2 = new ImageIcon(imgScale2);
        jLabel5.setIcon(scaleIcon2);
        }
   }
    public class TableOne
    {
        public TableOne(GiangVien gv)
        {
             defaultb = new DefaultTableModel()
                {
                    @Override
    public boolean isCellEditable(int row, int column) {
       //all cells false
       return false;
    }
         
             };
        jTable1.setModel(defaultb);
        defaultb.addColumn("Mã HP");
        defaultb.addColumn("Tên HP");
        defaultb.addColumn("Mã Lớp");
        List<ThongTinLop> mclass3= lopInf.getHPGV(gv.getIDGV());
        for(ThongTinLop tt : mclass3)
        {
            defaultb.addRow(new Object[]{tt.getMaHP(),tt.getTenHP(),tt.getIDLop()});
            
        }
        }
    }
    public class Table2
    {
        public Table2(GiangVien gv)
        {
            defaultb2 = new DefaultTableModel()
                {
                    @Override
    public boolean isCellEditable(int row, int column) {
       //all cells false
       return false;
    }
                };
        jTable2.setModel(defaultb2);
        defaultb2.addColumn("Thứ" );
        defaultb2.addColumn("Thời gian");
        defaultb2.addColumn("Mã Lớp");
        List<ThongTinLop> mclass2= lopInf.getTKB(gv.getIDGV());
        for(ThongTinLop tt : mclass2)
        {
            String st = new String();
            st =  (tt.getGioMD()).toString()+" - "+ (tt.getGioKT()).toString();
            defaultb2.addRow(new Object[]{tt.getThu(),st,tt.getIDLop() });
            
        }
        DefaultTableCellRenderer rightRenderer = new DefaultTableCellRenderer();
        rightRenderer.setHorizontalAlignment(SwingConstants.CENTER);
 
        TableModel tableModel = jTable2.getModel();
 
        for (int columnIndex = 0; columnIndex < tableModel.getColumnCount(); columnIndex++)
        {
            jTable2.getColumnModel().getColumn(columnIndex).setCellRenderer(rightRenderer);
        }
        }
    }
    public class Table3
    {
        public Table3(GiangVien gv)
        {
            defaultb3 = new DefaultTableModel()
                {
                    @Override
    public boolean isCellEditable(int row, int column) {
       //all cells false
       return false;
    }
                };
         jTable3.setModel(defaultb3);
        defaultb3.addColumn("Mã HP");
        defaultb3.addColumn("Tên HP");
        defaultb3.addColumn("Mã Lớp");
        List<ThongTinLop> mclass4= lopInf.getHPGV(gv.getIDGV());
        for(ThongTinLop tt : mclass4)
        {
            defaultb3.addRow(new Object[]{tt.getMaHP(),tt.getTenHP(),tt.getIDLop()});
            
        }
        }
    }
    public static class HeaderColor extends DefaultTableCellRenderer
    {
        public HeaderColor()
        {
            setOpaque(true);
        }
        public Component getTableCellRendererComponent(JTable mytable, Object value,boolean selected,boolean focused,int row,int column)
        {
            super.getTableCellRendererComponent(mytable, value, selected, focused, row, column);
            setBackground(new java.awt.Color(255,51,51));
            setForeground(new java.awt.Color(255,255,255));
            return this;
        }
        
    }
    public class table
    {
        public table()
        {
        jTable1.getTableHeader().setDefaultRenderer(new HeaderColor());
        jTable2.getTableHeader().setDefaultRenderer(new HeaderColor());
        jTable3.getTableHeader().setDefaultRenderer(new HeaderColor());
        jTable4.getTableHeader().setDefaultRenderer(new HeaderColor());
        jTable5.getTableHeader().setDefaultRenderer(new HeaderColor());
        jTable6.getTableHeader().setDefaultRenderer(new HeaderColor());
         JTableHeader tb3 = jTable1.getTableHeader();
        ((DefaultTableCellRenderer)tb3.getDefaultRenderer()).setHorizontalAlignment(JLabel.CENTER);
         JTableHeader tb4 = jTable2.getTableHeader();
        ((DefaultTableCellRenderer)tb4.getDefaultRenderer()).setHorizontalAlignment(JLabel.CENTER);
         JTableHeader tb5 = jTable3.getTableHeader();
        ((DefaultTableCellRenderer)tb5.getDefaultRenderer()).setHorizontalAlignment(JLabel.CENTER);
        JTableHeader tb6 = jTable4.getTableHeader();
        ((DefaultTableCellRenderer)tb6.getDefaultRenderer()).setHorizontalAlignment(JLabel.CENTER);
        
        JTableHeader tb7 = jTable5.getTableHeader();
        ((DefaultTableCellRenderer)tb7.getDefaultRenderer()).setHorizontalAlignment(JLabel.CENTER);
        
         JTableHeader tb1 = jTable6.getTableHeader();
        ((DefaultTableCellRenderer)tb1.getDefaultRenderer()).setHorizontalAlignment(JLabel.CENTER);
        }
        
    }
    public class table4
    {
        public table4()
        {
            
        if(LuaChon==0)
        {
            
             defaultb4 = new DefaultTableModel()
                {
                    @Override
    public boolean isCellEditable(int row, int column) {
       //all cells false
       return false;
    }
         
             };
             jTable4.setModel(defaultb4);
             defaultb4.addColumn("Mã HP");
             defaultb4.addColumn("Tên học phần");
             defaultb4.addColumn("Mã Lớp");
             defaultb4.addColumn("Mã GV");
           
             defaultb4.addColumn("số sinh viên");
             
        List<ThongTinLop> Lopkhoa = lopInf.LopKHoa(gv.getMaKhoa());
        for(ThongTinLop tt : Lopkhoa)
        {
            if(tt.getMaGV().equals("0")) defaultb4.addRow(new Object[]{tt.getMaHP(),tt.getTenHP(),tt.getIDLop(),"NULL",tt.getSiSo()});
            else 
            {
               
                defaultb4.addRow(new Object[]{tt.getMaHP(),tt.getTenHP(),tt.getIDLop(),tt.getMaGV(),tt.getSiSo()});
            }
          
            
        }
        
        jTable4.getColumnModel().getColumn(0).setPreferredWidth(50);
        jTable4.getColumnModel().getColumn(1).setPreferredWidth(170);
        jTable4.getColumnModel().getColumn(2).setPreferredWidth(50);
        jTable4.getColumnModel().getColumn(3).setPreferredWidth(50);
        jTable4.getColumnModel().getColumn(4).setPreferredWidth(70);
        
        jTable4.setAutoResizeMode(JTable.AUTO_RESIZE_LAST_COLUMN);
     
             
        }
        else
        {
            defaultb4 = new DefaultTableModel()
                {
                    @Override
    public boolean isCellEditable(int row, int column) {
       //all cells false
       return false;
    }
         
             };
             jTable4.setModel(defaultb4);
             defaultb4.addColumn("MSGV");
             defaultb4.addColumn("Họ Tên");
             defaultb4.addColumn("Ngày sinh");
             defaultb4.addColumn("Giới tính");
             user = new User();
             List<GiangVien> listGV = user.GvKhoa(gv.getMaKhoa());
        for(GiangVien tt : listGV)
        {
            String gt;
            if(gv.getGioiTinh()) gt = "Nam";
              else gt = "Nữ";
             defaultb4.addRow(new Object[]{tt.getIDGV(),tt.getNameGV(),tt.getNgaysinh(),gt});
          
            
        }
        jTable4.getColumnModel().getColumn(0).setPreferredWidth(50);
        jTable4.getColumnModel().getColumn(1).setPreferredWidth(170);
        jTable4.getColumnModel().getColumn(2).setPreferredWidth(80);
        jTable4.getColumnModel().getColumn(3).setPreferredWidth(50);
        
        jTable4.setAutoResizeMode(JTable.AUTO_RESIZE_LAST_COLUMN);
             
        }
            
        }
     
        
    }
    
 public class table6
 {
     public table6()
     {
         if(ChonKN==0)
         {
             defaultb6 = new DefaultTableModel()
                {
                    @Override
    public boolean isCellEditable(int row, int column) {
       //all cells false
       return false;
    }
                };
        jTable6.setModel(defaultb6);
        defaultb6.addColumn("STT");
        defaultb6.addColumn("Thời gian");
        defaultb6.addColumn("Hành động");
        defaultb6.addColumn("GV thay the");
        defaultb6.addColumn("Ma lop");
        defaultb6.addColumn("Lí do");
       
        SqlDuyet duyet = new SqlDuyet();
         List<DoiGV> day= duyet.ThongKeDonGVT(gv.getMaKhoa());
         int stt=1;
        for(DoiGV tt : day)
        {
            String hdong = new String();
            hdong = "Thay đổi giáo viên lớp ";
            defaultb6.addRow(new Object[]{stt,tt.getThoigiangui(),hdong,tt.getIdgv(),tt.getIdlop(),tt.getLido()});
            stt++;
            
        }
        jTable6.getColumnModel().getColumn(0).setPreferredWidth(30);
        jTable6.getColumnModel().getColumn(1).setPreferredWidth(100);
        jTable6.getColumnModel().getColumn(2).setPreferredWidth(200);
        jTable6.getColumnModel().getColumn(3).setPreferredWidth(200);
        jTable6.setAutoResizeMode(JTable.AUTO_RESIZE_LAST_COLUMN);
         }
         else if ( ChonKN==1)
         {
           
             defaultb6 = new DefaultTableModel()
                {
                    @Override
    public boolean isCellEditable(int row, int column) {
       //all cells false
       return false;
    }
                };
        jTable6.setModel(defaultb6);
        defaultb6.addColumn("STT");
        defaultb6.addColumn("Thời gian gui ");
        defaultb6.addColumn("Hành động");
       defaultb6.addColumn("GV thay the");
        defaultb6.addColumn("Ma lop");
        defaultb6.addColumn("Lí do");
        defaultb6.addColumn("Y/N");
       
        SqlDuyet duyet = new SqlDuyet();
         List<DoiGV> day= duyet.ThongKeDonDDGVT(gv.getMaKhoa());
         int stt=1;
        for(DoiGV tt : day)
        {
            String hdong = new String();
            hdong = "Thay đổi giáo viên lớp ";
            defaultb6.addRow(new Object[]{stt,tt.getThoigiangui(),hdong,tt.getIdgv(),tt.getIdlop(),tt.getLido(),tt.getDongy()});
            stt++;
            
        }
        jTable6.getColumnModel().getColumn(0).setPreferredWidth(30);
        jTable6.getColumnModel().getColumn(1).setPreferredWidth(100);
        jTable6.getColumnModel().getColumn(2).setPreferredWidth(200);
        jTable6.getColumnModel().getColumn(3).setPreferredWidth(200);
        jTable6.setAutoResizeMode(JTable.AUTO_RESIZE_LAST_COLUMN);
         }
         else if ( ChonKN==2)
         {
           
             defaultb6 = new DefaultTableModel()
                {
                    @Override
    public boolean isCellEditable(int row, int column) {
       //all cells false
       return false;
    }
                };
        jTable6.setModel(defaultb6);
         defaultb6.addColumn("STT");
        defaultb6.addColumn("Hành động");
        defaultb6.addColumn("loai diem");
        defaultb6.addColumn("diem truoc PK");
        defaultb6.addColumn("Mã lớp");
        defaultb6.addColumn("MSSV");
       
        
       
        SqlDuyet duyet = new SqlDuyet();
         List<DonPK> day= duyet.ThongKeDonGVTCDSV(Integer.parseInt(gv.getIDGV()));
         int stt=1;
        for(DonPK tt : day)
        {
            String hdong = new String();
           
                hdong = "Phúc khảo";
              
            defaultb6.addRow(new Object[]{stt,hdong,tt.getLoaidiem(),tt.getDiem_truocPK(),tt.getIdlop(),tt.getIdsv()});
            stt++;
            
        }
       
         }
         else if(ChonKN ==3)
         {
               defaultb6 = new DefaultTableModel()
                {
                    @Override
    public boolean isCellEditable(int row, int column) {
       //all cells false
       return false;
    }
                };
        jTable6.setModel(defaultb6);
         defaultb6.addColumn("STT");
        defaultb6.addColumn("Hành động");
        defaultb6.addColumn("loai diem");
        defaultb6.addColumn("diem truoc PK");
        defaultb6.addColumn("diem sau PK");
        defaultb6.addColumn("Mã lớp");
        defaultb6.addColumn("MSSV");
       
        
       
        SqlDuyet duyet = new SqlDuyet();
         List<DonPK> day= duyet.ThongKeDonGVTDD(Integer.parseInt(gv.getIDGV()));
         int stt=1;
        for(DonPK tt : day)
        {
            String hdong = new String();
           
                hdong = "Phúc khảo";
              
            defaultb6.addRow(new Object[]{stt,hdong,tt.getLoaidiem(),tt.getDiem_truocPK(),tt.getDiem_sauPK(),tt.getIdlop(),tt.getIdsv()});
            stt++;
            
        }
       
        
         }
     }
 }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JRadioButton jRadioButton5;
    private javax.swing.JRadioButton jRadioButton6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JTable jTable4;
    private javax.swing.JTable jTable5;
    private javax.swing.JTable jTable6;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
